files:
  - source: /Localisation/amethyst_en.ts
    translation: /Localisation/amethyst_%locale_with_underscore%.ts
    ignore:
      - /Localisation/tools
      - /Localisation/README.md
      - /Localisation/*.qm
    languages_mapping:
      locale_with_underscore:
        cs: cs
        de: de
        fr: fr
        it: it
        ja: ja
        nl: nl
        pl: pl
        ru: ru
        es-ES: es
        pt-PT: pt
        pt-BR: pt_BR
        zh-CN: zh
