files:
  - source: /Localisation/amethyst_en.ts
    translation: /Localisation/amethyst_%locale_with_underscore%.ts
    ignore:
      - /Localisation/tools
      - /Localisation/README.md
      - /Localisation/*.qm
